### ISSUE TITLE
GC problem

### ISSUE THREAD

**Issue by eduarddrenth** [UCLALibrary/docker-cantaloupe#111]
In version 1.4.7-3 I run into this issue:

oat-test_cantaloupe.1.u0rlde0up883@faubu1.coulon.nl    | [59.292s][warning][gc,alloc] qtp398887205-65: Retried waiting for GCLocker too often allocating 15863938 words

Tiles fail to load and every now and than the container restarts.

I tried increasing memory, no luck yet. One thing that may cause problems is the use of -Xmx, see #58 

I am still in the phase of analyzing the problem.

My docker setup is as follows:

```
  cantaloupe:
    image: uclalibrary/cantaloupe:4.1.7-3
    environment:
      - CANTALOUPE_LOG_APPLICATION_LEVEL=warn
    ports:
      - "8184:8182"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: "4GB"
```
