### ISSUE TITLE
cantaloupe.properties repeats all the entries each time docker restarts

### ISSUE THREAD

**Issue by mpapado3** [UCLALibrary/docker-cantaloupe#161]
Hello,

we run cantaloupe on docker and we have noticed that each time we restart cantaloupe docker container the cantaloupe.properties file appends all the set of properties to the end of the file.

![image](https://github.com/UCLALibrary/docker-cantaloupe/assets/17457738/74e57bb7-ae12-4e1c-86ee-0d1ea07deef1)

this is how we instantiate docker:

```
    image: uclalibrary/cantaloupe:5.0.5-7
    container_name: cantaloupe
    volumes:
      - ./storage/app/library:/imageroot
      - ./config/docker/cantaloupe/cantaloupe.properties:/etc/cantaloupe/cantaloupe.properties
      - ./config/docker/cantaloupe/delegates.rb:/etc/cantaloupe/delegates.rb
    environment:
      CANTALOUPE_ENDPOINT_ADMIN_ENABLED: 'true'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
    ports:
      - 8182:8182
    restart: always
```
